<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Table: tenants
     * -----------------------------------------------------------------
     * Represents one customer business using the NIRA POS platform.
     * Example: "Toko Baju Kupu-Kupu", "Laundry Bu Sari".
     *
     * This is the ROOT of the multi-tenant hierarchy:
     * tenants -> outlets -> users / products / transactions
     */
    public function up(): void
    {
        Schema::create('tenants', function (Blueprint $table) {
            $table->uuid('id')->primary(); // Generated by the model via HasUuids trait

            $table->string('business_name', 150);

            $table->string('business_type', 50)
                ->comment('retail | fashion | souvenir | laundry | coffee_shop | gym');

            $table->string('subscription_status', 20)
                ->default('trial')
                ->comment('trial | active | suspended');

            $table->timestamps(); // created_at & updated_at
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('tenants');
    }
};